# Generated by Django 6.0.1 on 2026-02-02 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destino', models.CharField(max_length=100)),
                ('fecha_partido', models.DateTimeField()),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6)),
                ('plazas_totales', models.PositiveIntegerField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='fotos_viajes/')),
            ],
        ),
    ]
